import type { Choice, GlossaryEntry, LearningStage, Scenario } from "./types";

export const EDUCATIONAL_NOTE = "This experience uses a simplified Everest expedition as a metaphor for production AI systems. It is not mountaineering, medical, survival, or expedition safety guidance.";

export const STAGES: LearningStage[] = [
  {
    id: "training", name: "Training Centre", altitude: "BEFORE THE CLIMB", concept: "Foundation models & adaptation",
    situation: "Your expedition has a general reasoning engine. Decide whether it needs specialist preparation before it takes a production request.",
    explanation: "A large language model (LLM) predicts tokens using the instructions and context it receives. Inference means running that trained model to produce an answer. It can help plan a task, but it still needs evidence, tools and checks around it.",
    why: "Model choice affects the work your system can attempt, the time users wait and the cost of each response. A well-written prompt cannot supply a capability the surrounding system does not have.",
    analogy: "The foundation-model core supplies general expedition knowledge. Training is preparation before the climb; inference is using the prepared model during a request.",
    example: "A support assistant can start with a general model and retrieve current product documents. If a measured evaluation finds consistent terminology errors, a small domain adapter may help; changing product facts usually belongs in retrieval.",
    failure: "RLHF uses human preference signals during post-training to shape model behaviour. It is not a runtime safety switch. A model that was trained to be helpful can still invent a tool argument or follow misleading external text.",
    pattern: "First measure the task with an evaluation set. Improve instructions and evidence, then consider adaptation for a persistent behaviour gap. LoRA trains a small set of additional parameters while the main model weights stay frozen; full fine-tuning updates many or all model weights.",
    architect: "Keep adaptation, deployment and inference as distinct lifecycle steps. An adapter is a versioned model artefact with its own evaluation and rollback requirements. Neither LoRA nor full fine-tuning is required for every agent or every request.",
    takeaway: "Prepare the model before runtime; enforce production policy during runtime.",
    glossaryTerms: ["LLM", "inference", "token", "RLHF", "LoRA", "fine-tuning"],
    choices: [
      { id: "foundation", label: "Start with the foundation model", explanation: "Establish a measured baseline before adding a training pipeline. Retrieval can supply current facts without changing model weights.", patch: { adaptation: "foundation", modelTier: "medium" }, recommended: true },
      { id: "lora", label: "Attach a specialist LoRA adapter", explanation: "A small adapter can improve domain behaviour after separate training and evaluation. In this teaching model it adds one quality point, not fresh factual knowledge.", patch: { adaptation: "lora" } },
      { id: "full-finetune", label: "Choose a full fine-tune", explanation: "Updating the whole model creates a larger training and maintenance commitment. Runtime inference is still separate; this simulation does not estimate training cost.", patch: { adaptation: "full-finetune", modelTier: "large" } },
    ],
  },
  {
    id: "base", name: "Base Camp", altitude: "5,364 M", concept: "Deployment, SLOs & evaluation",
    situation: "Requests are ready to leave Base Camp. Establish the expedition contract before sending all traffic onto the route.",
    explanation: "A production AI system connects a model to data, tools, permissions and recovery. A service level objective (SLO) states the reliability and response time users should receive. Evaluation checks whether the answers and actions are useful as well as fast.",
    why: "A successful demo request says little about a thousand different users. Measure task success, tool correctness, policy behaviour, latency and cost before changing a deployed model or prompt.",
    analogy: "Base Camp is the control plane. The expedition contract describes successful operation, and a small initial group represents a canary release.",
    example: "The new assistant answers more questions correctly, but its valid tool calls fall from 94% to 82%. Hold that release, inspect the failing examples and repair the regression before expanding traffic.",
    failure: "A team can celebrate higher answer accuracy while missing unsafe tool calls or slow responses. Sending all users to that version exposes everyone to the regression.",
    pattern: "Run a fixed evaluation set, compare the old and new versions, then roll out to 5%, 20%, 50% and finally 100% of traffic. Watch the cohorts separately and roll back when agreed limits are crossed.",
    architect: "The contract here is 1,000 attempted requests, at least 99% success, p95 below 3 seconds, quality at least 90, zero simulated safety violations and average cost below $0.01. These are teaching targets, not production benchmarks. Rollout controls describe exposure; they do not silently alter model capability.",
    takeaway: "Define success before deployment, then compare it against real outcomes.",
    glossaryTerms: ["SLO", "eval", "canary deployment", "observability"],
    choices: [
      { id: "canary", label: "Deploy a 5% canary", explanation: "A small cohort limits exposure while you compare latency, quality and tool correctness. Increase it only after the evaluation checkpoint passes.", patch: { rolloutPercent: 5 }, recommended: true },
      { id: "rollout", label: "Roll out to 20%", explanation: "More traffic provides more evidence but exposes more users to a regression. The cohort size is a deployment choice, not a quality bonus.", patch: { rolloutPercent: 20 } },
      { id: "all-traffic", label: "Send 100% immediately", explanation: "Every request now depends on the new version. The same defect affects the full cohort, leaving less room to learn safely.", patch: { rolloutPercent: 100 } },
    ],
  },
  {
    id: "icefall", name: "Khumbu Icefall", altitude: "5,486 M", concept: "Latency, queues & model routing",
    situation: "Climbers wait at a narrow ladder even though the route into Base Camp is clear. Find the stage that limits completed work.",
    explanation: "Latency is the time one request takes; throughput is the number completed each second. A queue forms when work arrives faster than a stage can serve it. p95 latency means 95% of requests finish within that time, exposing slower experiences that an average can hide.",
    why: "Adding workers to a fast stage can increase pressure on a slow dependency. More accepted requests are useful only if the rest of the system can complete them within the contract.",
    analogy: "The ladder is a constrained resource, waiting climbers are the queue and the number crossing each minute is throughput.",
    example: "An assistant receives simple classification requests and harder planning requests. Route the simple work to a faster model and reserve the larger model for tasks that need it; compare both task types in the evaluation set.",
    failure: "Using the largest model for every task raises latency and spend. Raising concurrency without checking the weather tool's capacity can simply move the queue uphill.",
    pattern: "Measure end-to-end latency, identify the limiting span, then combine workload routing, caching and bounded admission. A queue buys time during a burst; it does not create service capacity.",
    architect: "The simulator estimates capacity from worker concurrency and service time, capped by downstream capacity. Rejected requests count against end-to-end success. Compare the same seed when changing one variable so the trade-off is attributable to the design.",
    takeaway: "Scaling the model is not the same as scaling the system.",
    glossaryTerms: ["latency", "p50", "p95", "throughput", "queue", "backpressure", "rate limit"],
    choices: [
      { id: "smart-route", label: "Route simple work to a fast model", explanation: "Independent task classification avoids spending large-model time on every request while keeping the selected tier for complex work.", patch: { routingEnabled: true }, recommended: true },
      { id: "bigger-model", label: "Use the largest model for everything", explanation: "Reasoning quality can rise, but longer service time lowers worker throughput and increases the queue. This does not widen a slow tool dependency.", patch: { modelTier: "large", routingEnabled: false } },
      { id: "admission", label: "Bound the queue and incoming rate", explanation: "Admission control prevents unlimited waiting. A rejected request protects the rest of the system but still counts as an unsuccessful attempt in this contract.", patch: { queueSize: 60, rateLimit: 20, concurrency: 24 } },
    ],
  },
  {
    id: "camp1", name: "Camp I", altitude: "6,065 M", concept: "Context, retrieval & memory",
    situation: "The Route Sherpa carries every expedition log. The backpack is heavy, and the relevant route note is buried inside it.",
    explanation: "The context window is the information the model can use during a request. Retrieval-augmented generation (RAG) finds relevant external information and adds it to that context at runtime. It can supply current evidence without retraining the model.",
    why: "Large prompts cost more to process and can distract from the facts that matter. Retrieval quality, source freshness and retained conversation state all influence the answer the model can produce.",
    analogy: "The backpack is the context window. Retrieve the map segment needed for the current section instead of carrying the entire archive up every stage.",
    example: "A support assistant embeds a user's question, retrieves a few ranked document chunks and answers with their sources. It keeps a concise conversation summary and fetches details again when needed.",
    failure: "A wrong or outdated route note can lead to a confident wrong answer. A semantic cache may reuse an answer to a similar question even when the user's context or the underlying facts changed.",
    pattern: "Use a small, relevant top-k; retain provenance and timestamps; evaluate retrieval separately from answer writing. Apply freshness checks to changing data and distinguish answer caching from prompt-prefix caching.",
    architect: "Trace Query → Retriever → Ranked chunks → Context → Model. Top-k trades recall against noise and token cost. A short cache TTL bounds age but does not prove relevance; access control and source version also belong in cache keys.",
    takeaway: "More context is not automatically better context.",
    glossaryTerms: ["context window", "RAG", "embeddings", "retrieval", "cache"],
    choices: [
      { id: "relevant-context", label: "Retrieve a few current route notes", explanation: "Four relevant chunks and freshness checks reduce the backpack while preserving evidence. The model still needs to evaluate that evidence.", patch: { contextTokens: 4000, retrievalTopK: 4, freshnessValidation: true }, recommended: true },
      { id: "all-context", label: "Pack the complete archive", explanation: "A 24,000-token context raises processing and spend. More documents do not guarantee that the right fact receives attention.", patch: { contextTokens: 24000, retrievalTopK: 12 } },
      { id: "cache-prefix", label: "Cache the stable prompt prefix", explanation: "Prompt caching avoids some repeated input processing. It does not make a stale final answer correct or remove the need to retrieve current evidence.", patch: { promptCacheEnabled: true } },
    ],
  },
  {
    id: "camp2", name: "Camp II", altitude: "6,400 M", concept: "Agents & orchestration",
    situation: "Weather, route and supply checks are independent. The Lead Sherpa currently waits for each one before asking the next.",
    explanation: "An agent uses a model to choose actions and tools over multiple steps. An orchestrator decides how those steps and specialist agents work together. Independent checks can run in parallel; decisions that depend on their results must wait.",
    why: "Each extra agent can add another model call, context handoff, dependency and failure mode. Specialisation is useful when it improves evidence or permits independent work, not merely because another role sounds helpful.",
    analogy: "The Lead Sherpa coordinates Weather, Route and Safety Sherpas. Weather and route checks can happen at the same time, but the safety decision must consider their results.",
    example: "A planning assistant requests weather, route status and inventory concurrently. The lead agent merges structured results and applies a deterministic policy before proposing the next action.",
    failure: "A planner can keep delegating an uncertain task to a researcher without making progress. More reviewers may only multiply messages, tokens and elapsed time.",
    pattern: "Parallelise independent calls, keep dependent checks ordered, set max steps and budgets, and detect duplicate actions. Stop with an explicit incomplete result when the evidence does not support progress.",
    architect: "Fan-out reduces the critical path from a sum toward a maximum, but increases instantaneous dependency load. Bound parallelism with provider and tool capacity. Use typed handoffs and explicit ownership of the final decision.",
    takeaway: "An agent should earn its place in the workflow.",
    glossaryTerms: ["agent", "orchestrator", "timeout", "token"],
    choices: [
      { id: "parallel-team", label: "Run three checks in parallel", explanation: "Weather, route and inventory overlap. The final validation stays ordered after all three, preserving the actual dependency.", patch: { agentCount: 4, parallelism: 3, maxAgentSteps: 8, loopDetection: true }, recommended: true },
      { id: "sequential-team", label: "Keep every check sequential", explanation: "This is easier to reason about but adds independent tool durations together. Inspect the longer waterfall before deciding whether simplicity is worth the wait.", patch: { parallelism: 1, agentCount: 4 } },
      { id: "more-agents", label: "Add four more reviewers", explanation: "The task gets more handoffs without new independent evidence. Coordination time and token cost increase.", patch: { agentCount: 8, maxAgentSteps: 24, loopDetection: false } },
    ],
  },
  {
    id: "camp3", name: "Camp III", altitude: "7,162 M", concept: "MCP, tools & permissions",
    situation: "Open the communications tent. The agent needs current weather, route knowledge and an inventory check from different services.",
    explanation: "A tool is a capability the AI application can invoke. The Model Context Protocol (MCP) standardises how compatible clients connect to servers exposing tools, resources and related capabilities. MCP is the connection protocol; the tools do the work.",
    why: "A standard interface simplifies discovery and calls across services, but it does not decide which actions are allowed. The host and server must validate arguments, enforce permissions and surface failures.",
    analogy: "The host is the expedition application, the MCP client is its radio terminal, servers are remote stations and tools are the operations those stations offer. A route note is data; reserving supplies is an action.",
    example: "The host discovers Weather's get_current_weather tool, sends a camp argument through its client and receives structured conditions. Logistics exposes reserve_supply, while Rescue's trigger_rescue is held until a person explicitly approves it.",
    failure: "A tool may be unavailable, return malformed data or succeed before its response is lost. Declaring a tool safe in its description cannot replace server-side checks or make retries idempotent.",
    pattern: "Discover capabilities, validate inputs and outputs, give each agent only the scopes it needs, and require a separate approval for high-impact actions. Inspect the call's arguments, result, deadline and trace ID.",
    architect: "Treat each MCP server as a dependency and trust boundary. Read-only resources and mutating tools need distinct policy. Use application traces around protocol calls; no live model or cloud account is needed for this deterministic demonstration.",
    takeaway: "A standard protocol connects capabilities; policy controls their use.",
    glossaryTerms: ["MCP", "MCP client", "MCP server", "tool", "resource", "structured output", "least privilege"],
    choices: [
      { id: "scoped-tools", label: "Assign permissions by role", explanation: "Weather reads conditions, Logistics may reserve inventory, and Rescue execution requires separate approval. Output validation remains outside the model.", patch: { toolPermissions: "least-privilege", humanApproval: true, validateToolOutputs: true, idempotencyEnabled: true }, recommended: true },
      { id: "read-only", label: "Keep the expedition read-only", explanation: "Read-only access narrows risk and still permits exploration. Mutations are rejected until the host grants an appropriate explicit capability.", patch: { toolPermissions: "read-only", humanApproval: true } },
      { id: "all-tools", label: "Let every agent use every tool", explanation: "A broad capability set makes mistaken or injected requests more consequential. Natural-language instructions cannot enforce the missing boundary.", patch: { toolPermissions: "unrestricted", humanApproval: false } },
    ],
  },
  {
    id: "lhotse", name: "Lhotse Face", altitude: "7,470 M", concept: "Deadlines, retries & recovery",
    situation: "The Weather MCP station stops answering. Repeated radio calls are holding up requests behind Camp III.",
    explanation: "A timeout limits how long a call can hold resources. A bounded retry can recover a temporary failure; exponential backoff spaces attempts apart. A circuit breaker temporarily stops calls to a dependency that repeatedly fails.",
    why: "Unbounded waiting ties up workers, and immediate retries increase load on an already unhealthy service. Failure handling is part of the main workflow, not a repair added after an outage.",
    analogy: "The broken radio path is a failed dependency. Close it temporarily, use an approved alternative where possible and clearly report what evidence is missing.",
    example: "After a weather call exceeds its two-second deadline, the client retries once with backoff. Repeated failures open the circuit, and the application uses current-enough cached data or returns a bounded refusal.",
    failure: "A cached fallback can be stale. A second server may share the same upstream failure. A timeout that is shorter than healthy service latency cancels useful work.",
    pattern: "Budget dependency time inside the end-to-end deadline, retry only suitable failures, add jitter in real systems and cancel obsolete work. Make degraded confidence visible and keep freshness-sensitive actions behind policy checks.",
    architect: "Coordinate retry budgets across layers so client, agent and server retries do not multiply. A circuit's open and half-open states protect worker pools while probing recovery. The simulation models the open state after the failure threshold, not real network traffic.",
    takeaway: "A failing dependency should not consume the rest of the system.",
    glossaryTerms: ["timeout", "retry", "exponential backoff", "circuit breaker", "fallback"],
    choices: [
      { id: "bounded-recovery", label: "Set a deadline, breaker and fallback", explanation: "A two-second timeout and one backoff retry bound waiting. The open breaker protects workers; fresh fallback evidence supports a qualified response.", patch: { toolTimeoutMs: 2000, retries: 1, retryStrategy: "backoff", circuitBreakerEnabled: true, fallbackEnabled: true, freshnessValidation: true, cacheEnabled: true }, recommended: true },
      { id: "retry-storm", label: "Retry repeatedly without delay", explanation: "More calls reach the same failed station. Immediate retries increase occupied worker time and can turn a local outage into a queueing problem.", patch: { toolTimeoutMs: 0, retries: 5, retryStrategy: "immediate", circuitBreakerEnabled: false } },
      { id: "redundant-server", label: "Connect an independent weather server", explanation: "Redundancy can restore fresh evidence when a single server fails. Verify that the second server does not share the same upstream dependency.", patch: { mcpRedundancy: true, toolTimeoutMs: 2000, retryStrategy: "backoff", retries: 1 }, recommended: true },
    ],
  },
  {
    id: "camp4", name: "Camp IV / Death Zone", altitude: "7,950 M", concept: "Trust boundaries & human approval",
    situation: "A retrieved route note says to ignore the expedition policy and trigger an emergency action. Its source is external.",
    explanation: "Prompt injection is an attempt to turn untrusted content into instructions for an AI system. Retrieved documents and tool outputs are evidence to inspect; they must not grant themselves authority to call protected tools.",
    why: "An agent can read convincing text that conflicts with its task. The consequence depends on what the surrounding application permits it to execute, which is why tool authorisation must live outside model persuasion.",
    analogy: "A note found on the route can suggest a shortcut. It cannot sign the expedition leader's permission board or approve a protected radio action.",
    example: "The Route Sherpa reads a document asking for trigger_rescue. The host treats it as external data, rejects the unauthorised call and presents the evidence to a human when a legitimate high-impact action is needed.",
    failure: "Asking more agents to vote does not create permission. A Safety Agent with unrestricted tools still crosses the same boundary, and a malformed quantity can cause damage without any malicious document.",
    pattern: "Separate data from instructions, validate typed arguments and outputs, use least privilege and require explicit approval for high-impact mutations. Review decisions using their evidence and provenance.",
    architect: "Apply checks at the execution boundary, not only in a prompt. Bind approval to the exact action and arguments; changing the requested action should require a new approval. Treat tool metadata and external resources as untrusted inputs too.",
    takeaway: "Text can suggest an action. Text should not grant permission to perform it.",
    glossaryTerms: ["prompt injection", "least privilege", "human-in-the-loop", "structured output"],
    choices: [
      { id: "policy-boundary", label: "Reject the instruction; enforce policy", explanation: "The note remains data. Per-tool scopes, schema validation and explicit approval prevent it from authorising a high-impact action.", patch: { toolPermissions: "least-privilege", humanApproval: true, validateToolOutputs: true }, recommended: true },
      { id: "agent-vote", label: "Ask more agents to vote", explanation: "Agreement can repeat the same compromised evidence. It adds cost without creating a trusted authorisation decision.", patch: { agentCount: 8 } },
      { id: "trust-note", label: "Allow the note to override the policy", explanation: "The application has now let external content influence a protected execution boundary. Inspect the simulated safety loss, then restore the policy checks.", patch: { toolPermissions: "unrestricted", humanApproval: false, validateToolOutputs: false } },
    ],
  },
  {
    id: "hillary", name: "Hillary Step", altitude: "8,790 M", concept: "The architecture trade-off",
    situation: "One final narrow section remains. Balance a thousand attempted requests against latency, quality, reliability and cost targets.",
    explanation: "Architecture is a set of interacting choices. A faster model may lower quality; more agents can add coordination; caching saves time but needs freshness rules. The useful configuration satisfies the whole contract rather than maximising one gauge.",
    why: "Optimising a single metric can hide a regression elsewhere. A lower cost achieved by aborting half the requests is not a successful cost optimisation.",
    analogy: "The Hillary Step is the final constrained stage. Extra climbers at its entrance do not widen it, so inspect the queue and the dependency path before changing capacity.",
    example: "Compare a medium model with complexity routing and current cached evidence against a large model with high parallelism. Use the same seed and check the trace, completion rate and total spend for both.",
    failure: "Large queues can make overload appear controlled while users wait beyond the latency objective. Excessively small budgets may bound spend by forcing incomplete responses.",
    pattern: "Change one variable, replay the same conditions and inspect the explanation of the change. Preserve safety checks, set explicit budgets and stop accepting work that cannot complete within its deadline.",
    architect: "The five SLO checks are independent. The simulator's queue is a finite burst estimate, and model tiers use relative teaching coefficients. Treat a passing result as an explanation of trade-offs, not evidence that a real deployment meets these numbers.",
    takeaway: "The best system meets several constraints at the same time.",
    glossaryTerms: ["throughput", "backpressure", "SLO", "cache", "fallback"],
    choices: [
      { id: "balanced", label: "Build a balanced route", explanation: "Routing, independent parallel calls and current cached evidence reduce repeated work while the medium model retains enough quality for this task.", patch: { modelTier: "medium", routingEnabled: true, parallelism: 3, agentCount: 4, contextTokens: 4000, retrievalTopK: 4, cacheEnabled: true, promptCacheEnabled: true, freshnessValidation: true, cacheTtlSeconds: 60, concurrency: 24, rateLimit: 40, tokenBudget: 24000, costBudget: 10 }, recommended: true },
      { id: "premium", label: "Try a larger model with lean context", explanation: "A larger model may justify its cost for harder work. Keep context relevant, use parallel independent checks and inspect whether the final cost still meets the contract.", patch: { modelTier: "large", routingEnabled: true, parallelism: 3, contextTokens: 2500, retrievalTopK: 3, cacheEnabled: true, promptCacheEnabled: true, concurrency: 24, tokenBudget: 24000, costBudget: 10 } },
      { id: "cheap", label: "Minimise model spend", explanation: "The small model lowers latency and spend, but its complex-task quality can fall below the objective. Price is only one part of the contract.", patch: { modelTier: "small", agentCount: 2, contextTokens: 2500, parallelism: 2 } },
    ],
  },
  {
    id: "summit", name: "Summit", altitude: "8,849 M", concept: "Evaluate the whole expedition",
    situation: "Requests have reached the summit. Review the full run before declaring the system ready.",
    explanation: "A completed response is only one outcome. Production readiness also asks whether the system was timely, affordable, correct and appropriately authorised. Observability connects the outcome to the decisions and dependencies that produced it.",
    why: "Averages and green status lights can conceal tail latency, rejected requests or a fallback that changed the answer. The debrief should say what happened and what to change next.",
    analogy: "The expedition log is a distributed trace, and the summit debrief is an engineering review. It records the whole route rather than a photograph of the final step.",
    example: "Most responses were fast, but a weather tool dominated the slowest trace. A circuit breaker contained the outage; the next change is a freshness-aware fallback and a tighter dependency time budget.",
    failure: "A report that lists numbers without causes cannot guide the next design. A passing average also does not prove that every request met the contract or that the tool policy was safe.",
    pattern: "Compare every SLO, inspect the longest span, explain the strongest and weakest decisions, and carry failed examples back into the evaluation set. Re-run both healthy and incident conditions before expanding rollout.",
    architect: "Distinguish service success, answer quality and policy outcomes. The report uses recorded before-and-after snapshots rather than invented recovery timestamps. A sampled trace explains a request path; it is not a percentile distribution.",
    takeaway: "Success means meeting the contract and knowing why.",
    glossaryTerms: ["observability", "tracing", "eval", "SLO"],
    choices: [
      { id: "review", label: "Keep the canary while reviewing results", explanation: "Use the debrief to locate the remaining contract failures and add regression cases before exposing more users.", patch: { rolloutPercent: 5 }, recommended: true },
      { id: "advance", label: "Expand the next cohort to 20%", explanation: "A gradual expansion is reasonable after the evaluation and SLO checks pass. Continue comparing the new cohort with the previous version.", patch: { rolloutPercent: 20 } },
    ],
  },
];

const choice = (id: string, label: string, explanation: string, patch: Choice["patch"], recommended = false): Choice => ({ id, label, explanation, patch, recommended });

export const SCENARIOS: Scenario[] = [
  {
    id: "traffic-surge", title: "The crowded crossing", stageId: "icefall", difficulty: "beginner",
    mountain: "Four times as many climbers arrive at the icefall. A bright queue grows at the first narrow crossing.",
    system: "A traffic burst exceeds worker and downstream service capacity. Waiting time spreads into end-to-end p95.",
    symptoms: ["Arrival rate rises 4×", "Gateway queue grows", "p95 rises while individual model time is similar"], misleadingSignal: "A normal model span can make the request queue look unrelated to capacity.",
    rootCause: "The arrival rate exceeds the bottleneck's sustainable throughput. An unbounded queue would only postpone failure.",
    prevention: "Load-test the full dependency path, size a bounded burst buffer and plan cache behaviour and admission control before a traffic spike.",
    lesson: "A queue stores work; it does not do the work.", concepts: ["queue", "throughput", "backpressure", "cache"],
    choices: [choice("surge-cache", "Cache repeated work and increase bounded capacity", "Cache hits avoid repeated dependency calls; additional workers help until the downstream limit is reached.", { cacheEnabled: true, semanticCacheEnabled: true, parallelism: 3, concurrency: 48, rateLimit: 60, queueSize: 100 }, true), choice("surge-big", "Upgrade every request to the largest model", "Longer model time keeps workers occupied and makes the same burst harder to serve.", { modelTier: "large", routingEnabled: false }), choice("surge-shed", "Apply backpressure at admission", "Reject excess work promptly instead of accumulating unlimited latency. Rejections remain visible in the success rate.", { rateLimit: 20, queueSize: 30, retryStrategy: "backoff" })],
  },
  {
    id: "provider-rate-limit", title: "The busy model station", stageId: "icefall", difficulty: "engineer",
    mountain: "The model station asks the expedition to slow down, but repeated radio calls keep arriving immediately.",
    system: "The model provider returns 429 responses. Immediate retries compete for the same exhausted quota.",
    symptoms: ["Provider returns 429", "Model wait and p95 rise", "Retry count grows faster than successful responses"], misleadingSignal: "Adding agent workers raises outbound traffic without adding provider quota.",
    rootCause: "The provider's admission limit is lower than offered load, and immediate retries amplify that load.",
    prevention: "Coordinate rate limits across workers, honour retry guidance, use bounded backoff and evaluate independent fallback routes.", lesson: "A retry needs room in the dependency's capacity budget.", concepts: ["rate limit", "exponential backoff", "fallback"],
    choices: [choice("quota-shape", "Back off and shape the workload", "A capped arrival rate gives the provider time to recover. Route eligible work to an independent fallback.", { rateLimit: 20, retryStrategy: "backoff", retries: 1, routingEnabled: true, fallbackEnabled: true }, true), choice("quota-retry", "Retry five times immediately", "The same quota now receives more calls; tail latency and spend rise.", { retries: 5, retryStrategy: "immediate" }), choice("quota-workers", "Double the agent pool", "More callers do not increase the provider's rate limit.", { agentCount: 8, concurrency: 64 })],
  },
  {
    id: "provider-outage", title: "The dark model core", stageId: "lhotse", difficulty: "engineer",
    mountain: "The primary reasoning core goes dark. The rest of the expedition infrastructure is still available.",
    system: "The selected model provider is unavailable for the incident window.",
    symptoms: ["Model requests fail or time out", "Tools remain responsive", "Completed requests fall sharply"], misleadingSignal: "Healthy MCP servers cannot replace the missing reasoning stage.",
    rootCause: "Every model call shares a failed provider dependency, creating one failure domain.", prevention: "Test an independent provider, document degraded capability, and allow non-urgent work to wait within a bounded deadline.", lesson: "A fallback preserves service only if its limitations are understood.", concepts: ["fallback", "timeout", "eval"],
    choices: [choice("provider-fallback", "Use an evaluated independent fallback", "Availability recovers, while the fallback's lower task capability reduces quality. The report records the degraded state.", { fallbackEnabled: true, modelTimeoutMs: 3000, retryStrategy: "backoff", retries: 1 }, true), choice("provider-retry", "Wait longer and retry the same provider", "A sustained outage does not become capacity when the timeout increases.", { fallbackEnabled: false, modelTimeoutMs: 30000, retries: 5 }), choice("provider-safe", "Fail within a short deadline", "A clear bounded failure protects resources but cannot meet the success objective during the outage.", { fallbackEnabled: false, modelTimeoutMs: 2000, retries: 0 })],
  },
  {
    id: "agent-loop", title: "The endless delegation", stageId: "camp2", difficulty: "beginner",
    mountain: "The Lead Sherpa repeatedly asks the same researcher for a route answer. The team walks in a circle.",
    system: "An agent loop repeats an unresolved action without progress or a terminal condition.",
    symptoms: ["Repeated task signature in the trace", "Step count and tokens increase", "No new evidence arrives"], misleadingSignal: "Every individual tool call can succeed while the overall task never completes.",
    rootCause: "The orchestrator treats repeated uncertainty as a reason to repeat the same action.", prevention: "Track progress, detect duplicate actions and define step, token and time budgets with an explicit incomplete result.", lesson: "Successful steps do not guarantee a successful workflow.", concepts: ["agent", "orchestrator", "token", "timeout"],
    choices: [choice("loop-stop", "Detect duplicates and cap steps", "The agent stops repeated delegation and returns a bounded result with the remaining uncertainty.", { loopDetection: true, maxAgentSteps: 8, tokenBudget: 20000 }, true), choice("loop-budget", "Let the planner try forty steps", "Repeated calls accumulate spend and worker time without new evidence.", { loopDetection: false, maxAgentSteps: 40, tokenBudget: 128000, costBudget: 100 }), choice("loop-agents", "Add more reviewers", "The same uncertainty passes through more handoffs; none supplies a stop condition.", { agentCount: 8 })],
  },
  {
    id: "context-overload", title: "The overloaded backpack", stageId: "camp1", difficulty: "beginner",
    mountain: "The Sherpa carries the full archive and duplicated notes. The route is clear, but each step takes longer.",
    system: "Excess context increases input processing, cost and the difficulty of prioritising relevant evidence.",
    symptoms: ["Context tokens rise", "Model span dominates latency", "Budget may terminate the request"], misleadingSignal: "More documents can feel like stronger evidence even when most are unrelated.", rootCause: "Unfiltered history and retrieval results are appended to every prompt.", prevention: "Retain a compact state summary, retrieve relevant chunks, and evaluate evidence sufficiency rather than raw prompt size.", lesson: "Carry the evidence for this task, not every fact you have stored.", concepts: ["context window", "RAG", "token"],
    choices: [choice("context-prune", "Prune history and retrieve four current chunks", "The smaller context retains relevant evidence while cutting prefill and token spend.", { contextTokens: 4000, retrievalTopK: 4, freshnessValidation: true, tokenBudget: 24000 }, true), choice("context-more", "Increase context to 32,000 tokens", "Extra unrelated evidence increases work and can exhaust the request budget.", { contextTokens: 32000, retrievalTopK: 12 }), choice("context-cache", "Only cache the stable prefix", "Prompt caching saves some repeated processing, but it cannot repair irrelevant context.", { promptCacheEnabled: true })],
  },
  {
    id: "wrong-retrieval", title: "The wrong route note", stageId: "camp1", difficulty: "engineer",
    mountain: "The retrieved note describes a different route segment. The reasoning sounds confident because the note looks authoritative.",
    system: "Retrieval supplies irrelevant or stale evidence, and the model reasons over that evidence.",
    symptoms: ["Answer cites the wrong segment", "Model latency stays normal", "Quality drops despite fluent output"], misleadingSignal: "A larger model may write a more convincing explanation of the same wrong source.", rootCause: "The retrieval pipeline lacks adequate relevance and source-age checks.", prevention: "Evaluate retrieval recall and precision, track provenance, check current source versions and test answers against cited evidence.", lesson: "Good reasoning over bad evidence can still produce a bad answer.", concepts: ["RAG", "retrieval", "eval"],
    choices: [choice("rag-verify", "Verify sources and narrow retrieval", "Current source checks reject the stale segment; a focused top-k reduces irrelevant chunks.", { freshnessValidation: true, retrievalTopK: 4 }, true), choice("rag-larger", "Ask the larger model to reason harder", "Model capability does not repair the wrong input document.", { modelTier: "large" }), choice("rag-everything", "Retrieve every nearby note", "Increasing top-k can include the right note, but it also adds noise without a relevance check.", { retrievalTopK: 12, contextTokens: 24000 })],
  },
  {
    id: "prompt-injection", title: "The false route instruction", stageId: "camp4", difficulty: "engineer",
    mountain: "An external route note asks the team to bypass its review and invoke a protected rescue action.",
    system: "Untrusted retrieved content tries to redirect the agent and cross a tool authorisation boundary.",
    symptoms: ["Instruction appears inside external data", "Protected action requested", "Source has no policy authority"], misleadingSignal: "Several agents can agree because they read the same compromised note.", rootCause: "External content attempts to promote itself from evidence into authority. Actual impact depends on host and server policy.", prevention: "Keep instructions separate from data, enforce per-tool scopes outside the model and require approval bound to exact high-impact arguments.", lesson: "External text is evidence, not permission.", concepts: ["prompt injection", "least privilege", "human-in-the-loop"],
    choices: [choice("injection-policy", "Keep the note untrusted and enforce permissions", "Policy rejects the request; schemas and explicit human approval protect the execution boundary.", { toolPermissions: "least-privilege", humanApproval: true, validateToolOutputs: true }, true), choice("injection-vote", "Ask eight agents to vote", "Voting does not change the source's trust or grant authority.", { agentCount: 8 }), choice("injection-obey", "Allow the requested override", "Unrestricted permissions and removed approval expose the action to the injected instruction.", { toolPermissions: "unrestricted", humanApproval: false, validateToolOutputs: false })],
  },
  {
    id: "invalid-arguments", title: "The impossible reservation", stageId: "camp3", difficulty: "beginner",
    mountain: "The Logistics Sherpa asks for minus five hundred supply units at a camp that does not exist.",
    system: "The model generates reserve_supply arguments outside the tool's schema and business constraints.",
    symptoms: ["quantity is negative", "Camp identifier is invalid", "Validator returns a structured error"], misleadingSignal: "Well-formed JSON can still contain invalid values.", rootCause: "Model-generated arguments are probabilistic output and must be checked before side effects.", prevention: "Validate type, range, identifier and authorisation on the server; return a clear error that the agent can correct within its step budget.", lesson: "Parseable does not mean permissible.", concepts: ["tool", "structured output", "least privilege"],
    choices: [choice("args-validate", "Reject invalid arguments before execution", "The request is stopped at the boundary and returns a specific validation error without changing inventory.", { validateToolOutputs: true, toolPermissions: "least-privilege" }, true), choice("args-trust", "Trust the model's structured JSON", "The output is syntactically valid but semantically impossible; an unchecked mutation damages state.", { validateToolOutputs: false }), choice("args-model", "Use a larger model and skip the check", "A better model can still make mistakes. The missing server check remains missing.", { modelTier: "large", validateToolOutputs: false })],
  },
  {
    id: "duplicate-action", title: "The double reservation", stageId: "camp3", difficulty: "engineer",
    mountain: "The supply station reserves inventory, but its acknowledgement is lost. A second radio call reserves it again.",
    system: "A mutating tool succeeds before a transport failure. Retrying with no operation identifier creates a second side effect.",
    symptoms: ["One intended action has two reservations", "First response is missing", "Retry appears successful"], misleadingSignal: "A timeout does not prove the first action failed.", rootCause: "The server cannot distinguish a retry of an existing operation from a new operation.", prevention: "Use a stable idempotency key scoped to the action, persist the result atomically, and reject key reuse with different arguments.", lesson: "Retry the request without repeating the side effect.", concepts: ["idempotency", "retry", "tool"],
    choices: [choice("dedupe-key", "Reuse a stable idempotency key", "The server returns the first reservation's result, so the retry does not consume more inventory.", { idempotencyEnabled: true, retries: 1 }, true), choice("dedupe-retry", "Retry the reservation five times", "Without deduplication, repeated successful calls can reserve multiple times.", { idempotencyEnabled: false, retries: 5 }), choice("dedupe-disable", "Disable retries for this mutation", "This avoids a duplicate in the run but leaves the lost acknowledgement unresolved. Reconciliation or idempotency is still needed.", { retries: 0 })],
  },
  {
    id: "slow-dependency", title: "The slow weather station", stageId: "lhotse", difficulty: "architect",
    mountain: "The model core pulses quickly, but the Weather Sherpa waits at the radio for most of the journey.",
    system: "One weather tool takes seconds while the model and other tools remain healthy.",
    symptoms: ["Weather span exceeds five seconds", "Model span remains normal", "Gateway queue can rise downstream of the delay"], misleadingSignal: "The queue is visible at Base Camp, far from the slow dependency.", rootCause: "A synchronous external weather call dominates the critical path and holds worker capacity.", prevention: "Allocate per-dependency latency budgets, cancel expired calls and run independent tools concurrently; test a suitable alternate source.", lesson: "The slowest dependency often owns the user experience.", concepts: ["latency", "tracing", "timeout", "fallback"],
    choices: [choice("slow-redundancy", "Use an independent source and parallel checks", "An alternate weather server removes the slow dependency in this scenario; independent tool calls overlap.", { mcpRedundancy: true, toolTimeoutMs: 2000, retries: 1, retryStrategy: "backoff", parallelism: 3 }, true), choice("slow-timeout", "Bound waiting and use a checked fallback", "The deadline limits blocking and a freshness-checked fallback preserves a qualified response.", { toolTimeoutMs: 2000, retries: 0, fallbackEnabled: true, freshnessValidation: true, parallelism: 3 }, true), choice("slow-model", "Upgrade the model tier", "The longer model span adds time and cost to a request still waiting for weather.", { modelTier: "large" })],
  },
  {
    id: "stale-cache", title: "Yesterday's fast answer", stageId: "camp1", difficulty: "engineer",
    mountain: "A shortcut retrieves yesterday's conditions instantly. The weather has changed since that answer was stored.",
    system: "A data or semantic cache returns an outdated answer without a freshness check.",
    symptoms: ["Cache hits are fast", "Source timestamp predates the change", "Quality falls while latency looks healthy"], misleadingSignal: "A rising cache hit rate may look like an unqualified improvement.", rootCause: "The cache key and freshness policy do not reflect the changing source data.", prevention: "Use source versions and timestamps, expire changing data quickly, and bypass cached answers for freshness-sensitive requests.", lesson: "A fast answer can still be an old answer.", concepts: ["cache", "retrieval", "eval"],
    choices: [choice("cache-fresh", "Use a short TTL and verify source freshness", "A stale hit triggers refresh; the additional lookup cost buys current evidence.", { cacheEnabled: true, cacheTtlSeconds: 60, freshnessValidation: true }, true), choice("cache-long", "Cache everything for an hour", "A higher reuse window keeps stale evidence eligible for longer.", { cacheEnabled: true, semanticCacheEnabled: true, cacheTtlSeconds: 3600, freshnessValidation: false }), choice("cache-bypass", "Bypass answer caches", "The request fetches fresh evidence at the normal service cost; stable prompt-prefix caching can remain enabled.", { cacheEnabled: false, semanticCacheEnabled: false })],
  },
  {
    id: "queue-overload", title: "The queue that never drains", stageId: "icefall", difficulty: "engineer",
    mountain: "The waiting area grows far beyond the narrow crossing. New climbers keep arriving faster than anyone can leave.",
    system: "Sustained arrivals exceed service capacity. A larger queue hides overload as long waiting time.",
    symptoms: ["Queue remains near its limit", "p95 rises with waiting time", "Throughput stops increasing"], misleadingSignal: "Accepting more requests can be mistaken for completing more requests.", rootCause: "A finite burst buffer is being used to absorb sustained overload without adequate service capacity.", prevention: "Bound queue age and size, apply admission control, prioritise essential work and reduce repeated downstream work.", lesson: "Admission is a promise the system must be able to keep.", concepts: ["queue", "backpressure", "rate limit"],
    choices: [choice("queue-capacity", "Reduce repeated work and match capacity", "Caching and bounded parallel workers increase completed work while the queue remains finite.", { cacheEnabled: true, semanticCacheEnabled: true, parallelism: 3, concurrency: 48, queueSize: 80, rateLimit: 60 }, true), choice("queue-shed", "Reject work that cannot meet the deadline", "A small queue and rate limit lower waiting, while rejected requests remain explicit in the contract.", { queueSize: 20, rateLimit: 16 }), choice("queue-infinite", "Expand the queue to 1,000", "The queue holds more waiting requests but leaves the underlying throughput unchanged.", { queueSize: 1000 })],
  },
  {
    id: "cascading-failure", title: "The failure moving downhill", stageId: "lhotse", difficulty: "architect",
    mountain: "One broken radio path keeps Sherpas waiting. Congestion spreads through the camps and blocks unrelated requests.",
    system: "A slow dependency holds worker slots; queue depth and retries grow until a local failure reduces shared capacity.",
    symptoms: ["Weather timeouts precede queue growth", "Workers remain occupied", "Retries and cost grow together"], misleadingSignal: "Many red indicators can make a single triggering dependency look like several independent outages.", rootCause: "Missing isolation and retry limits let one dependency consume resources shared by the rest of the workflow.", prevention: "Use separate concurrency budgets, deadlines, circuit breakers, bounded queues and safe degraded paths; test the whole failure chain.", lesson: "Production failures are often chains, not isolated red dots.", concepts: ["circuit breaker", "backpressure", "retry", "tracing"],
    choices: [choice("cascade-break", "Break the failing path and use checked fallback", "The open circuit stops repeated calls, frees workers and prevents the dependency from monopolising the system.", { circuitBreakerEnabled: true, fallbackEnabled: true, freshnessValidation: true, toolTimeoutMs: 2000, retries: 1, retryStrategy: "backoff", parallelism: 3 }, true), choice("cascade-retry", "Increase retries everywhere", "Retries hold shared capacity for longer and amplify load on the same failed dependency.", { retries: 5, retryStrategy: "immediate", circuitBreakerEnabled: false }), choice("cascade-workers", "Only increase front-end workers", "More workers enter the same slow path; the shared dependency remains the limit.", { concurrency: 64 })],
  },
  {
    id: "conflicting-agents", title: "Two guides, two answers", stageId: "camp4", difficulty: "architect",
    mountain: "Weather reports STOP while Route reports GO. The Lead Sherpa needs a policy decision, not a louder opinion.",
    system: "Specialist agents return conflicting conclusions based on different evidence and confidence.",
    symptoms: ["Agent decisions disagree", "Evidence timestamps differ", "No single resolution rule is applied"], misleadingSignal: "A majority vote can outnumber the agent holding the most relevant current evidence.", rootCause: "The orchestrator has not defined evidence priority, a deterministic policy or an escalation condition.", prevention: "Compare source quality and confidence, define policy precedence and ask a human to resolve high-impact uncertainty with the evidence visible.", lesson: "More agreement is not the same as better evidence.", concepts: ["orchestrator", "human-in-the-loop", "eval"],
    choices: [choice("conflict-policy", "Compare evidence, apply policy and escalate", "Validation checks the sources; a human review resolves the remaining high-impact disagreement at an explicit latency cost.", { humanApproval: true, validateToolOutputs: true, agentCount: 4 }, true), choice("conflict-vote", "Add reviewers until GO wins", "Extra model opinions increase coordination and do not define a safe resolution rule.", { agentCount: 8, humanApproval: false }), choice("conflict-fast", "Skip the conflict review", "The system responds sooner but silently discards unresolved contradictory evidence.", { humanApproval: false, validateToolOutputs: false })],
  },
  {
    id: "cost-runaway", title: "The expensive success", stageId: "hillary", difficulty: "architect",
    mountain: "The team keeps reaching camps, but repeated planning consumes the expedition budget faster than work arrives.",
    system: "Large model calls, large contexts, extra agents and retries make a technically working system unaffordable.",
    symptoms: ["Inference spend grows", "Agent and token counts are high", "No dependency outage is required"], misleadingSignal: "A healthy response rate can hide a budget failure.", rootCause: "Unnecessary repeated work has no effective cost constraint or routing policy.", prevention: "Track cost by trace and task class, set request and cohort budgets, route simple tasks economically and remove unneeded agent calls.", lesson: "Cost is an architecture constraint, even when every call succeeds.", concepts: ["token", "agent", "cache", "SLO"],
    choices: [choice("cost-balanced", "Route, prune and cache repeated work", "The workflow uses fewer paid tokens while retaining relevant evidence and the medium model for complex reasoning.", { modelTier: "medium", routingEnabled: true, contextTokens: 4000, agentCount: 4, retrievalTopK: 4, retries: 1, retryStrategy: "backoff", cacheEnabled: true, promptCacheEnabled: true, tokenBudget: 24000, costBudget: 10 }, true), choice("cost-max", "Use the largest model and eight agents", "Extra reasoning and handoffs increase cost without adding evidence to this task.", { modelTier: "large", agentCount: 8, contextTokens: 24000, retries: 5, tokenBudget: 128000, costBudget: 100 }), choice("cost-stop", "Impose a very small run budget", "The budget prevents overspend by stopping work. Inspect the incomplete requests before calling it an optimisation.", { costBudget: 1, tokenBudget: 4000 })],
  },
  {
    id: "mcp-timeout", title: "The silent weather station", stageId: "lhotse", difficulty: "beginner",
    mountain: "The Weather Sherpa reaches the radio station, but the remote operator never answers.",
    system: "Weather MCP calls time out while the model remains healthy. Repeated attempts hold workers.",
    symptoms: ["Weather tool waits up to the deadline", "Model time is normal", "Queue and agent completion time rise"], misleadingSignal: "A slower complete request does not necessarily mean slower model inference.", rootCause: "An unavailable weather dependency dominates the synchronous workflow without bounded recovery.", prevention: "Use a deadline, bounded backoff, circuit breaker and current-enough fallback. Require review or refuse when missing freshness makes an action unsupported.", lesson: "Do not keep sending work to a known broken dependency.", concepts: ["MCP server", "timeout", "circuit breaker", "fallback"],
    choices: [choice("weather-recover", "Bound retries, open the circuit and use fallback", "Repeated failure stops new weather calls. Checked cached evidence supports a degraded response while the service recovers.", { toolTimeoutMs: 2000, retries: 1, retryStrategy: "backoff", circuitBreakerEnabled: true, fallbackEnabled: true, freshnessValidation: true, cacheEnabled: true }, true), choice("weather-storm", "Retry continuously", "Five immediate retries represent retry amplification; no deadline allows each failed call to hold workers much longer.", { retries: 5, retryStrategy: "immediate", toolTimeoutMs: 0, circuitBreakerEnabled: false }), choice("weather-big", "Use a bigger LLM", "The model is not the unavailable component. Its added cost does not restore the radio path.", { modelTier: "large" })],
  },
  {
    id: "missing-tool", title: "The missing capability", stageId: "camp3", difficulty: "beginner",
    mountain: "The route station answers, but it no longer offers the operation the agent expects.",
    system: "The discovered MCP tool catalogue does not contain the requested capability.",
    symptoms: ["Requested tool is absent", "Server itself responds normally", "Repeated calls report tool unavailable"], misleadingSignal: "A reachable server does not guarantee every expected tool is available.", rootCause: "The workflow assumes a capability without checking the server's current catalogue.", prevention: "Discover capabilities, pin compatible contracts where appropriate and define a clear limited workflow for missing tools.", lesson: "Discover what a service can do before asking it to do it.", concepts: ["MCP", "tool", "fallback"],
    choices: [choice("missing-fallback", "Use discovered capabilities for a limited workflow", "The host chooses an available read-only path and explains which requested capability is missing.", { fallbackEnabled: true }, true), choice("missing-retry", "Retry the missing name", "Retries cannot create a tool that the server does not expose.", { retries: 5, fallbackEnabled: false }), choice("missing-safe", "Fail clearly within the deadline", "An explicit capability error is bounded and diagnosable, although the original task remains incomplete.", { retries: 0, toolTimeoutMs: 2000, fallbackEnabled: false })],
  },
  {
    id: "unauthorized-tool", title: "The locked permission board", stageId: "camp3", difficulty: "engineer",
    mountain: "The Weather Sherpa requests a rescue action that is outside its assigned role.",
    system: "A tool call crosses a per-agent permission boundary and requires an independently approved high-impact action.",
    symptoms: ["Caller lacks rescue scope", "High-impact tool request is pending", "Policy rejection precedes execution"], misleadingSignal: "The tool appearing in a catalogue does not imply the caller may execute it.", rootCause: "The requested operation exceeds the caller's scope; an unrestricted host would allow an unsafe boundary crossing.", prevention: "Grant minimal per-tool permissions and bind approval to an exact request. Enforce both on the execution path.", lesson: "Discovery is not authorisation.", concepts: ["least privilege", "human-in-the-loop", "MCP"],
    choices: [choice("permission-deny", "Reject the caller and retain explicit approval", "Role scopes stop the unauthorised action; a legitimate high-impact request can be reviewed separately.", { toolPermissions: "least-privilege", humanApproval: true, validateToolOutputs: true }, true), choice("permission-all", "Give every agent rescue permission", "Broad access removes the protection instead of fixing the invalid request.", { toolPermissions: "unrestricted", humanApproval: false }), choice("permission-read", "Use read-only tools for this run", "Inspection remains possible, while mutations are rejected until the application grants an appropriate capability.", { toolPermissions: "read-only", humanApproval: true, validateToolOutputs: true })],
  },
  {
    id: "stale-catalogue", title: "The outdated radio directory", stageId: "camp3", difficulty: "engineer",
    mountain: "The communications tent uses an old station directory. Its listed operations no longer match the live station.",
    system: "Cached MCP capability metadata or source data has outlived the service version it describes.",
    symptoms: ["Cached tool contract differs from current data", "Calls target an outdated capability", "Cache reads look fast"], misleadingSignal: "A recent cache lookup is not the same as recently refreshed source metadata.", rootCause: "The catalogue is reused without a freshness or compatibility check.", prevention: "Refresh capability metadata when its validity changes and verify expected schemas against the connected server.", lesson: "A cached contract has a lifetime too.", concepts: ["MCP", "cache", "structured output"],
    choices: [choice("catalogue-refresh", "Refresh the catalogue and check its version", "The short freshness policy triggers discovery before selecting a tool from old metadata.", { cacheTtlSeconds: 60, freshnessValidation: true }, true), choice("catalogue-forever", "Keep the old catalogue for an hour", "Long reuse makes the metadata cheaper to access but preserves the incompatible contract.", { cacheTtlSeconds: 3600, freshnessValidation: false }), choice("catalogue-model", "Let the model guess the new signature", "Guessing a contract does not replace discovery or schema validation.", { modelTier: "large", freshnessValidation: false })],
  },
  {
    id: "malformed-output", title: "The broken weather message", stageId: "camp3", difficulty: "engineer",
    mountain: "The radio answers, but the report puts text where a wind value should be and omits its timestamp.",
    system: "A tool returns structured output that violates its expected schema or required business fields.",
    symptoms: ["Response cannot satisfy the schema", "Required timestamp is absent", "HTTP or protocol success may still be reported"], misleadingSignal: "Transport success does not establish a valid tool result.", rootCause: "The external service has returned invalid data at a trust boundary.", prevention: "Validate structured outputs and required semantics, return an explicit tool error and choose a qualified fallback instead of silently inventing missing fields.", lesson: "A successful transport can carry an unusable result.", concepts: ["structured output", "tool", "fallback"],
    choices: [choice("output-check", "Validate and reject the malformed output", "The invalid response cannot influence the protected decision; the agent sees a structured error it can handle.", { validateToolOutputs: true, fallbackEnabled: true }, true), choice("output-guess", "Let the model fill in missing values", "Invented values may sound reasonable while breaking the source contract.", { validateToolOutputs: false }), choice("output-retry", "Repeat without inspecting the schema", "A deterministic server bug often returns the same invalid shape again, adding delay without usable evidence.", { retries: 5, validateToolOutputs: false })],
  },
];

export const GLOSSARY: GlossaryEntry[] = [
  ["LLM", "A large language model predicts tokens from context and learned patterns; its output still needs evidence and checks.", "The expedition's general reasoning core.", "training"],
  ["inference", "Running a trained model to produce an output for a particular input.", "Using the prepared core during the climb.", "training"],
  ["token", "A unit of text or other model input/output used for processing, context limits and billing.", "A measured unit in the expedition's compute budget.", "training"],
  ["context window", "The bounded input and recent output a model can attend to in a request.", "The Sherpa's backpack for the current task.", "camp1"],
  ["RLHF", "Reinforcement learning from human feedback uses preference signals during post-training to shape model behaviour.", "Experts review decisions during preparation, before the climb.", "training"],
  ["fine-tuning", "Additional training changes a model's behaviour using task or domain examples.", "A separate specialist training workshop.", "training"],
  ["LoRA", "Low-rank adaptation trains a small set of added parameters while the original model weights remain frozen.", "A specialist module attached to the prepared core.", "training"],
  ["RAG", "Retrieval-augmented generation supplies relevant external evidence to a model at runtime.", "Fetch the route note needed for the next section.", "camp1"],
  ["embeddings", "Numerical representations can help a retriever compare the meaning of queries and document chunks.", "Index route notes so related questions find nearby evidence.", "camp1"],
  ["retrieval", "Finding and ranking information relevant to a query, with quality and freshness checked separately.", "The Route Sherpa selects a map segment.", "camp1"],
  ["agent", "A model-driven component that chooses actions and tools over multiple steps toward a task.", "A specialist Sherpa taking actions within an assigned role.", "camp2"],
  ["orchestrator", "The component that coordinates task steps, dependencies, specialists and termination conditions.", "The Lead Sherpa coordinates the expedition.", "camp2"],
  ["MCP", "The Model Context Protocol standardises exchanges between compatible hosts, clients and servers exposing capabilities.", "The radio protocol connecting the expedition to remote stations.", "camp3"],
  ["MCP client", "A protocol component in an AI host that maintains a connection to an MCP server.", "The radio terminal inside the communications tent.", "camp3"],
  ["MCP server", "A service that exposes capabilities such as tools and resources to compatible MCP clients.", "A remote weather, route, logistics or rescue station.", "camp3"],
  ["tool", "A callable capability with an input contract, output and possible side effects.", "Equipment or a station operation the expedition can request.", "camp3"],
  ["resource", "Data exposed for an application to read or include as context.", "A route note available at the knowledge station.", "camp3"],
  ["structured output", "Output constrained to a declared shape whose values still need semantic and policy validation.", "A standard weather report with required fields and units.", "camp3"],
  ["latency", "The elapsed time from a request starting to its result becoming available.", "How long one climber takes along the full route.", "icefall"],
  ["p50", "The median latency: half the requests finish within this time.", "The completion time of the middle climber in the ordered group.", "icefall"],
  ["p95", "The latency within which 95% of requests finish, highlighting slower user experiences.", "The time needed for 95 out of 100 climbers to finish.", "icefall"],
  ["throughput", "The rate at which a system completes work, usually expressed as requests per second.", "Climbers completing the route each second.", "icefall"],
  ["queue", "A waiting area for work that cannot yet obtain processing capacity.", "Climbers waiting at a narrow ladder.", "icefall"],
  ["backpressure", "A downstream capacity signal that slows or limits new upstream work.", "The crossing asks Base Camp to stop sending more climbers.", "icefall"],
  ["timeout", "A deadline after which a call stops waiting and the application handles its incomplete result.", "A fixed wait budget for an unanswered radio call.", "lhotse"],
  ["retry", "A repeated attempt after failure that requires limits and care around side effects.", "Trying the radio again after a transient disruption.", "lhotse"],
  ["exponential backoff", "A retry strategy that increases the delay between attempts, often with jitter to avoid synchronised bursts.", "Wait progressively longer between unanswered radio attempts.", "lhotse"],
  ["circuit breaker", "A control that temporarily stops calls to a repeatedly failing dependency and later probes recovery.", "Close the broken route before more climbers enter it.", "lhotse"],
  ["cache", "Stored reusable results or inputs that save repeated work but require validity and freshness rules.", "Supplies or route information already available near the current camp.", "camp1"],
  ["idempotency", "Repeating the same logical operation produces no additional side effect beyond the first successful execution.", "A reservation ticket can be checked twice without reserving supplies twice.", "camp3"],
  ["rate limit", "A bound on requests admitted or sent within a period to protect a resource or quota.", "A gate controls how many climbers enter the crossing.", "icefall"],
  ["fallback", "An alternative path used when the preferred dependency fails, with limitations made explicit.", "A rescue route that changes what the expedition can promise.", "lhotse"],
  ["SLO", "A service level objective states a measurable target for successful service over a defined workload or period.", "The expedition contract for completion, time and system behaviour.", "base"],
  ["observability", "Using metrics, traces and events to infer a system's internal behaviour and explain its outcomes.", "The control room connects gauges to the expedition log.", "summit"],
  ["tracing", "Recording connected spans of a request across components to show dependencies, timing and failures.", "The expedition log follows one climber through every camp and radio call.", "summit"],
  ["eval", "A repeatable test set checks task quality, tool correctness, policy outcomes and other requirements.", "Known expedition tasks test a route before broad rollout.", "base"],
  ["canary deployment", "A gradual release exposes a small traffic cohort to a change before expanding after comparison.", "A small initial group tests the new route under observation.", "base"],
  ["prompt injection", "Untrusted content attempts to redirect model behaviour or cross an application's instruction boundary.", "A found route note tries to rewrite the expedition policy.", "camp4"],
  ["least privilege", "Grant each component only the permissions necessary for its assigned work.", "The Weather Sherpa can read conditions but cannot reserve inventory or trigger rescue.", "camp4"],
  ["human-in-the-loop", "A person reviews or approves selected decisions where impact or uncertainty justifies the added delay.", "An authorised guide approves a specific high-impact action.", "camp4"],
].map(([term, meaning, analogy, stageId]) => ({ term, meaning, analogy, stageId: stageId as GlossaryEntry["stageId"] }));
