"use client";

import { useState } from "react";

/*
  CalibrationBars — the reported calibration numbers from one independent
  study (scienthoon/jev-ood-calibration, Sept 2026). ECE = expected calibration
  error: how far stated confidence is from actual accuracy. Lower is better.
*/

const PUBLIC = [
  { name: "OpenBookQA (500)", ece: 0.024, acc: "94.2%" },
  { name: "CommonsenseQA (1,221)", ece: 0.032, acc: "88.1%" },
  { name: "HellaSwag (2,000)", ece: 0.029, acc: "86.1%" },
];
const NEW = [
  { name: "Queue (choice)", ece: 0.082, acc: "89.0%" },
  { name: "Angry? (yes/no)", ece: 0.079, acc: "91.7%" },
  { name: "Priority (score)", ece: 0.325, acc: "44.7%" },
];

export function CalibrationBars() {
  const [tab, setTab] = useState<"pub" | "new">("pub");
  const rows = tab === "pub" ? PUBLIC : NEW;
  const floor = tab === "new" ? 0.024 : null;

  return (
    <figure className="not-prose my-8 rounded-2xl border border-zinc-200 dark:border-zinc-800 bg-gradient-to-b from-zinc-50 to-white dark:from-zinc-900/60 dark:to-zinc-950 overflow-hidden">
      <div className="border-b border-zinc-200 dark:border-zinc-800 px-4 py-2.5 text-xs font-semibold text-zinc-500 dark:text-zinc-400">
        How far off is the stated confidence? (lower is better)
      </div>
      <div className="p-4 sm:p-5">
        <div className="flex gap-1.5">
          <button onClick={() => setTab("pub")} className={`rounded-full border px-2.5 py-1 text-[11px] ${tab === "pub" ? "border-zinc-900 dark:border-zinc-100 bg-zinc-900 dark:bg-zinc-100 text-white dark:text-zinc-900" : "border-zinc-200 dark:border-zinc-700 text-zinc-500"}`}>Public benchmarks</button>
          <button onClick={() => setTab("new")} className={`rounded-full border px-2.5 py-1 text-[11px] ${tab === "new" ? "border-zinc-900 dark:border-zinc-100 bg-zinc-900 dark:bg-zinc-100 text-white dark:text-zinc-900" : "border-zinc-200 dark:border-zinc-700 text-zinc-500"}`}>Tasks it could not have seen</button>
        </div>

        <ul className="mt-4 space-y-3">
          {rows.map((r) => (
            <li key={r.name}>
              <div className="flex justify-between text-[12px] text-zinc-700 dark:text-zinc-200"><span>{r.name}</span><span>accuracy {r.acc} · ECE <b>{r.ece.toFixed(3)}</b></span></div>
              <div className="relative mt-1 h-3 rounded bg-zinc-200 dark:bg-zinc-800">
                <div className={`h-3 rounded ${r.ece > 0.1 ? "bg-rose-500" : r.ece > 0.05 ? "bg-amber-500" : "bg-emerald-500"}`} style={{ width: `${(r.ece / 0.35) * 100}%` }} />
                {floor && <div className="absolute top-[-2px] h-[16px] border-l-2 border-dashed border-zinc-500" style={{ left: `${(floor / 0.35) * 100}%` }} title="noise floor" />}
              </div>
            </li>
          ))}
        </ul>
        {floor && <p className="mt-1 text-[10px] text-zinc-400">Dashed line: noise floor of a perfectly calibrated model on this sample (0.024).</p>}

        <div className="mt-4 rounded-xl border border-zinc-200 dark:border-zinc-800 p-3 text-[13px] leading-relaxed text-zinc-700 dark:text-zinc-200">
          {tab === "pub"
            ? "On well-known public benchmarks, which a model may well have seen in training, the confidence looks respectable. That is the flattering test."
            : "On 900 tickets generated by a script on 19 Sept 2026, so the model could not have seen them, calibration was worse: 0.107 overall, 4.4 times the noise floor. The priority label depended on a company rule that is not in the ticket text, so no model could know it. Jev still averaged 0.74 probability on its pick and was right 44.7% of the time."}
        </div>
        <p className="mt-2 text-[11px] text-zinc-500">Authors&rsquo; advice: do not threshold on the separate confidence field, calibrate per question rather than per model, and treat the output as a ranking until you have calibrated it locally.</p>
      </div>
    </figure>
  );
}
